### ISSUE TITLE
Ruby cucumber-compatibility-kit test failures

### ISSUE THREAD

**Issue by felixonmars** [cucumber/compatibility-kit#21]
### ✅ What did you expect to see?

Test failures when running the test suite:

```
...FFF.........

Failures:

  1) Cucumber::CompatibilityKit#gherkin_examples returns the list of gherkin examples
     Failure/Error:
       expect(Cucumber::CompatibilityKit.gherkin_examples)
         .to match_array(gherkin_examples)

       expected collection contained:  ["attachments", "data-tables", "examples-tables", "hooks", "minimal", "parameter-types", "pending", "retry", "rules", "skipped", "stack-traces", "undefined", "unknown-parameter-type"]
       actual collection contained:    []
       the missing elements were:      ["attachments", "data-tables", "examples-tables", "hooks", "minimal", "parameter-types", "pending", "retry", "rules", "skipped", "stack-traces", "undefined", "unknown-parameter-type"]
     # ./spec/cucumber-compatibility-kit_spec.rb:53:in `block (3 levels) in <top (required)>'

  2) Cucumber::CompatibilityKit#markdown_examples returns the list of markdown examples
     Failure/Error:
       expect(Cucumber::CompatibilityKit.markdown_examples)
         .to match_array(markdown_examples)

       expected collection contained:  ["markdown"]
       actual collection contained:    []
       the missing elements were:      ["markdown"]
     # ./spec/cucumber-compatibility-kit_spec.rb:60:in `block (3 levels) in <top (required)>'

  3) Cucumber::CompatibilityKit#all_examples returns the list of all available examples
     Failure/Error:
       expect(Cucumber::CompatibilityKit.all_examples)
         .to match_array(gherkin_examples + markdown_examples)

       expected collection contained:  ["attachments", "data-tables", "examples-tables", "hooks", "markdown", "minimal", "parameter-types", "pending", "retry", "rules", "skipped", "stack-traces", "undefined", "unknown-parameter-type"]
       actual collection contained:    []
       the missing elements were:      ["attachments", "data-tables", "examples-tables", "hooks", "markdown", "minimal", "parameter-types", "pending", "retry", "rules", "skipped", "stack-traces", "undefined", "unknown-parameter-type"]
     # ./spec/cucumber-compatibility-kit_spec.rb:67:in `block (3 levels) in <top (required)>'

Finished in 0.02696 seconds (files took 0.10428 seconds to load)
15 examples, 3 failures

Failed examples:

rspec ./spec/cucumber-compatibility-kit_spec.rb:52 # Cucumber::CompatibilityKit#gherkin_examples returns the list of gherkin examples
rspec ./spec/cucumber-compatibility-kit_spec.rb:59 # Cucumber::CompatibilityKit#markdown_examples returns the list of markdown examples
rspec ./spec/cucumber-compatibility-kit_spec.rb:66 # Cucumber::CompatibilityKit#all_examples returns the list of all available examples
```

### 📦 Which tool/library version are you using?

Ruby 3.0.4
rspec 3.11.0

### 📚 Any additional context?

Looks like the features dir contains files with ".feature.rb" extension instead of ".feature", which is what the library tests for. I am not sure which one should be changed here, though.

**Comment by felixonmars** [comment]
Turns out I need to run `npm run copy-to:ruby` before building the gem. Sorry for the noise!

**Comment by mpkorstanje** [comment]
That doesn't seem quite so obvious to me. Earmarking this for investigation.
